################################################                         
# 
# Makefile
# for virtio_crypto
#
# Stefanos Gerangelos <sgerag@cslab.ece.ntua.gr>
# Dimitris Siakavaras <jimsiak@cslab.ece.ntua.gr>
#
# ################################################

# C compiler to use for building userspace applications
CC = gcc

# Remove comment to enable verbose output from the kernel build system
KERNEL_VERBOSE = 'V=1'
DEBUG = y

# Add your debugging flag (or not) to CFLAGS
# Warnings are errors.
ifeq ($(DEBUG),y)
  EXTRA_CFLAGS += -g -DDEBUG=1 -Werror
else
  EXTRA_CFLAGS += -DDEBUG=0 -Werror
endif

# Extra CFLAGS used to compile the userspace helpers
# # e.g., -m32 if compiling in a 64-bit environment.
USER_CFLAGS = -Wall -Werror #-m32

obj-m := virtio_crypto.o
virtio_crypto-objs := crypto-module.o crypto-chrdev.o crypto-vq.o crypto-ioctl.o

all: modules test_crypto 

KERNELDIR ?= /lib/modules/$(shell uname -r)/build
PWD := $(shell pwd)

modules:
	make -C $(KERNELDIR) M=$(PWD) modules

test_crypto: test_crypto.c
	$(CC) $(USER_CFLAGS) -o $@ test_crypto.c

clean:
	make -C $(KERNELDIR) M=$(PWD) clean
	rm -f test_crypto
